services:
  # define services
  api:
    # builds container from dev dockerfile
    build:
      context: .
      dockerfile: Dockerfile.dev
    # map host port to container port
    ports:
      - "3009:3009"
    # load environment variables
    env_file:
      - .env
    # ensure db starts first
    depends_on:
      - db
    # mount source code to hot reload
    volumes:
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./src:/app/src
      - /app/node_modules
    command: npm run dev

  db:
    # pull postrgresql image
    image: postgres:16
    # load environment variables
    env_file:
      - .env
    # set "login" for database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # store database in volume outside container
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
